### ISSUE TITLE
Chart visual fixes

### ISSUE THREAD

**Issue by quocble** [quantadex/react_quantadex#1]
1. Top left text is visible, should say Volume
2. Hide market closed text
3. Hide symbol top left
4. top right symbol is not visible, format same way as the header
5. 1D is not working
6. Collapse top left

**Comment by TinyMolecule** [comment]
Can you include picture of elements you're talking about?

**Comment by quocble** [comment]
item 4: @TinyMolecule 
![image](https://user-images.githubusercontent.com/696643/49965178-4ee43a00-fed1-11e8-91d7-4984a9a16302.png)
