### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by jeee** [quantadex/react_quantadex#100]
Can't login with private key. I get the following error.

![Screenshot_20190326_004925](https://user-images.githubusercontent.com/6225833/54961459-05d86300-4f61-11e9-8a5d-5e23c8cc0099.png)

**Comment by jeee** [comment]
![Screenshot_20190326_005201](https://user-images.githubusercontent.com/6225833/54961559-77b0ac80-4f61-11e9-9080-f2cbec5ac24f.png)

**Comment by quocble** [comment]
@jeee  please try again.. i think this is related to issue with using key not found in the network.

**Comment by quocble** [comment]
Is it multisig?

**Comment by jeee** [comment]
yes, has different owner and active keys

**Comment by quocble** [comment]
confirmed, not an issue
