### ISSUE TITLE
Android pre-launch items

### ISSUE THREAD

**Issue by quocble** [quantadex/react_quantadex#136]
List it should have before launching this:

- [x] fix broken icons
- [x] add back button support
- [x] test code injection (Quoc)
a) https://github.com/TruckMovers/cordova-plugin-remote-injection
b) https://stackoverflow.com/questions/21984688/how-to-get-access-to-phonegap-api-from-a-remote-page
c) https://github.com/markmarijnissen/cordova-app-loader
- [x] login flow
- [x] lighter background colors (not pure black)
- [x] sign the package (Quoc)
- [x] publish it to s3
- [x] android landing page (SKIP FOR NOW)
- [x] hide tabbar when keyboard is up https://stackoverflow.com/questions/43739545/hide-tabs-on-keyboard-open
- [x] After login, switch to the wallet page
- [x] maintain login state across apps closes

### Login
- [x] mobile app - remove skip to download locally
- [x] auto-login for user (mobileapp) Replace main button as Continue (and hide the other button)
- [x] larger fonts on connect. (Use font 20px)
- [x] logout prompts a warning message about resetting credentials, and ask user to backup if necessary from settings.
- [x] settings -> export private key -> provide bip58 key, and WIF key.
- [x] android:allowBackup added to config so it backs up in google between app reinstall (Q)
- [x] Provide application key via Android settings (Q)

### Deployment 
- [x] playstore app bar (togglable) on the top
- [x] road test over the weekend
- [x] play store setup
https://www.npmjs.com/package/cordova-plugin-nativestorage#retrieving_values

**Comment by jeee** [comment]
make background color adjustable (other colors as well? font size? scale?)

**Comment by quocble** [comment]
@TinyMolecule 

REMARKS ANDROID APP

Is there a way to change to test network to test trades?
Use my own public key > make text clickable ass well
Private key > also make scan-able option?
Create wallet > tried to verify email, got captcha then just shows the ‘verify email’ button and nothing seems to happen.
Markets > ? icon next to depth not clickable
Markets > search box does not work
This does not have a bar with the blockchain info. Maybe create a page/tab for that?
Clicking the news item ‘Buy BTC with your credit card (4-3) opens page with white background and can’t go back except exit
The other news items only changes color, does nothing
Charts seem to need quite some load time(data/bandwidth?). Is there an option to cache that?
