### ISSUE TITLE
bch and ltc links are pointing to etherscan

### ISSUE THREAD

**Issue by shahpoo415** [quantadex/react_quantadex#137]
LTC url - https://live.blockcypher.com/ltc

BCH url - https://explorer.bitcoin.com/bch

**Comment by shahpoo415** [comment]
BCH url testnet - https://explorer.bitcoin.com/tbch

**Comment by shahpoo415** [comment]
LTC url testnet - https://chain.so/testnet/ltc

**Comment by quocble** [comment]
done, i think.
