### ISSUE TITLE
Add a trade button next to each wallet asset

### ISSUE THREAD

**Issue by quocble** [quantadex/react_quantadex#156]
![image](https://user-images.githubusercontent.com/696643/57954112-e0a00b00-78a6-11e9-9d8f-1e14dd407f2d.png)

![image](https://user-images.githubusercontent.com/696643/57951061-e8a77d00-789d-11e9-937d-867134cae1e1.png)

This is a button in binance which I find it useful.  We can generate the same for all asset in the wallet, and pair with each of the 4 markets we have available. (Use the markets configuration to find these markets)

**Comment by jeee** [comment]
unlisted coins don't show in the wallet if you don't have them. That way buyers could not find them via this route
