### ISSUE TITLE
orderbook alignment

### ISSUE THREAD

**Issue by jeee** [quantadex/react_quantadex#20]
The orderbook now shows the highest ask and you need to scroll to see the best ask. It should display the best ask and it needs to be visible that it is scroll-able.

**Comment by quocble** [comment]
@TinyMolecule  On QDEX/ETH market , the sell order (top), scrolled to the top, hiding the best price.

- Sell order should always scroll to bottom
- Display scrollbar if it is scrollable

Example from Switcheo:
![image](https://user-images.githubusercontent.com/696643/51636028-0aef4680-1f0d-11e9-94ca-e68a61a28f30.png)
