### ISSUE TITLE
Incorrectly displaying "canceled" for filled limit orders

### ISSUE THREAD

**Issue by Ken0sis** [quantadex/react_quantadex#58]
**Steps to reproduce:**
1. BUY order is placed
2. Order its on the order book
3. Order gets filled

**Observed Result:**
History section shows two separate lines for this transaction.  One line shows the order getting filled, and another line showing the limit order getting canceled.

**Expected Result:**
History should show is one line for this transaction, showing that it got filled.

Note: This phenomenon doesn't seem to happen if we perform a SELL instead of a BUY.

**Comment by quocble** [comment]
Bitshares seems to be cancelling orders when amount is zero. Seems only happen if i place an buy order for a high price, and sell at a low price... 

```
bool maybe_cull_small_order( database& db, const limit_order_object& order )
{
   /**
    *  There are times when the AMOUNT_FOR_SALE * SALE_PRICE == 0 which means that we
    *  have hit the limit where the seller is asking for nothing in return.  When this
    *  happens we must refund any balance back to the seller, it is too small to be
    *  sold at the sale price.
    *
    *  If the order is a taker order (as opposed to a maker order), so the price is
    *  set by the counterparty, this check is deferred until the order becomes unmatched
    *  (see #555) -- however, detecting this condition is the responsibility of the caller.
    */
   if( order.amount_to_receive().amount == 0 )
   {
      if( order.deferred_fee > 0 && db.head_block_time() <= HARDFORK_CORE_604_TIME )
      { // TODO remove this warning after hard fork core-604
         wlog( "At block ${n}, cancelling order without charging a fee: ${o}", ("n",db.head_block_num())("o",order) );
         db.cancel_limit_order( order, true, true );
      }
      else
         db.cancel_limit_order( order );
      return true;
   }
   return false;
}
```

**Comment by quocble** [comment]
@TinyMolecule  It looks like system cancelled orders when orders are too small, we can detect when

operation_result: "[0,{}]",

https://wya99cec1d.execute-api.us-east-1.amazonaws.com/testnet/account?filter_field=operation_type&filter_value=2,4&size=10&account_id=1.2.15

**Comment by quocble** [comment]
https://wya99cec1d.execute-api.us-east-1.amazonaws.com/testnet/account?filter_field=operation_type&filter_value=2&size=10&account_id=1.2.15

**Comment by quocble** [comment]
Verified.

**Comment by Ken0sis** [comment]
Fixed.  Much less confusing to read the Order History.  Thank you.
