### ISSUE TITLE
Improvement: Rename "ID" column

### ISSUE THREAD

**Issue by Ken0sis** [quantadex/react_quantadex#61]
**Current**
There is a column called "ID" under Open Orders, but it is not clear if this is a block ID, transaction ID, or some other kind of ID.

**Proposal**
Rename this column to either "Transaction ID" or "Transaction #" or some other shorthand, but definitely denote that this ID is for a transaction.

**Comment by quocble** [comment]
Call it Order ID

**Comment by Ken0sis** [comment]
Now naming is consistent, and easier to read trading workflows.  Thank you.
