### ISSUE TITLE
Improvement: Add close or X button withdraw/deposit popup

### ISSUE THREAD

**Issue by Ken0sis** [quantadex/react_quantadex#62]
**Current**
When users go to Wallet, and then click Withdraw or Deposit on any listed token, they will see this menu popping up.  However, there is no way to close this menu unless the user click on the same Withdraw or Deposit button again.
<img width="996" alt="image" src="https://user-images.githubusercontent.com/7650304/53462683-8e62f280-39f9-11e9-986e-ef04737d0c45.png">

**Proposal**
Add "Close" or "X" button on upper right hand of the popup so that it is more intuitive on how to close it.

**Comment by quocble** [comment]
Verified.

**Comment by Ken0sis** [comment]
It closes. Thank you!
